In [2]:
import numpy as np
a = np.genfromtxt('NSE-SBIN.csv', delimiter=',', dtype=str)
data=a[1:,:] # Remove the first row
print(data)

[['1/4/2019' '292.1' '299' ... '297.65' '19514041' '57796.86']
 ['1/3/2019' '295' '295.55' ... '291.1' '17548347' '51393.24']
 ['1/2/2019' '299.1' '302.5' ... '293.9' '25559853' '76220.1']
 ...
 ['3/25/1998' '285' '290.25' ... '289.15' '3632600' '10436.93']
 ['3/24/1998' '282' '288.4' ... '284.35' '4979900' '14231.55']
 ['3/23/1998' '278.45' '280.9' ... '279.95' '591700' '1654.91']]


In [3]:
print("Sum of all OPEN Stock Price :",sum(np.array(data[...,1],dtype=float)))
print("Maximum Open Stock Price :",max(np.array(data[...,1],dtype=float)))
print("Minimum Open Stock Price :",min(np.array(data[...,1],dtype=float)))


Sum of all OPEN Stock Price : 5068877.600000004
Maximum Open Stock Price : 3505.0
Minimum Open Stock Price : 142.85


In [4]:
print("Maximum Trade Quantity :",max(np.array(data[...,6],dtype=int)))
print("Minimum Trade Quantity :",min(np.array(data[...,6],dtype=int)))

Maximum Trade Quantity : 262677081
Minimum Trade Quantity : 3633


In [5]:
maxT=np.array(data[...,6],dtype=int)
np.where(maxT==maxT.max())
#print("Maximum Trade Quantity : ",data[296])
print("Maximum Trade Quantity Date : ",data[296][0])

Maximum Trade Quantity Date :  10/25/2017


In [6]:
maxT=np.array(data[...,6],dtype=int)
np.where(maxT==maxT.min())
#print("Maximum Trade Quantity : ",data[296])
print("Minimum Trade Quantity Date : ",data[4342][0])

Minimum Trade Quantity Date :  7/23/2001


In [7]:
maxT=np.array(data[...,2],dtype=float)
np.where(maxT==maxT.max())
#print("Maximum Trade Quantity : ",data[296])
print("Maximum Share Price Date : ",data[2022][0])

Maximum Share Price Date :  11/8/2010


In [8]:
maxT=np.array(data[...,3],dtype=float)
np.where(maxT==maxT.min())
#print("Maximum Trade Quantity : ",data[296])
print("Minimum Share Price Date : ",data[4300][0])

Minimum Share Price Date :  9/21/2001


In [9]:
year=np.array(data[...,0])
#print(year)

def fun(a):
    temp=a.split('/')
    return temp[2] 

Ydata=np.vectorize(fun)
year=Ydata(year)

print(data[np.where(year=='2019')])

[['1/4/2019' '292.1' '299' '291.5' '297.3' '297.65' '19514041' '57796.86']
 ['1/3/2019' '295' '295.55' '290.1' '291.05' '291.1' '17548347'
  '51393.24']
 ['1/2/2019' '299.1' '302.5' '293.1' '293.8' '293.9' '25559853' '76220.1']
 ['1/1/2019' '297.5' '300.7' '293.85' '300.7' '299.6' '11837127'
  '35128.77']]


### **Get indices of N maximum values in a NumPy array?**

In [10]:
arr = np.array([1, 3, 2, 4, 5])
print(arr)
print(arr.argsort())
print(arr.argsort()[-3:])
print(arr.argsort()[-3:][::-1])  #Reverse Logic
a=arr.argsort()[-3:][::-1]
for i in a:
    print (arr[i],end=" ")

[1 3 2 4 5]
[0 2 1 3 4]
[1 3 4]
[4 3 1]
5 4 3 

In [16]:
import heapq
a = np.array([12, 53, 62, 34, 95])
heapq.nlargest(3, range(len(a)), a.take)

[4, 2, 1]

In [91]:
x = np.array([11, 22, 43, 84, 95, 46])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [11 22 43 84 95 46]
Maximum Values:  4
Minimum Values:  0


In [92]:
x = np.array([[10,32,45],[33,3,54],[4,56,39]])
print("Original array: \n",x)
print("Maximum Values: ",np.argmax(x[...,0]))
print("Maximum Values: ",np.argmax(x[...,1]))
print("Maximum Values: ",np.argmax(x[...,2]))

print("Minimum Values: ",np.argmin(x[...,0]))
print("Minimum Values: ",np.argmin(x[...,1]))
print("Minimum Values: ",np.argmin(x[...,2]))


Original array: 
 [[10 32 45]
 [33  3 54]
 [ 4 56 39]]
Maximum Values:  1
Maximum Values:  2
Maximum Values:  1
Minimum Values:  2
Minimum Values:  1
Minimum Values:  2


In [93]:
#print("Maximum Values: ",np.argmax(np.array(data[...,1],dtype=float)))

print (data[np.argmax(np.array(data[...,1],dtype=float))])
print (data[np.argmin(np.array(data[...,1],dtype=float))])

['11/8/2010' '3505' '3515' '3413.25' '3425.8' '3425.15' '1752791'
 '60462.49']
['9/24/2001' '142.85' '147.95' '142.85' '146.9' '146.4' '415435' '606.1']


In [98]:
print(data)
import pandas as pd
import collections
a=pd.to_datetime(data[...,0])
date = np.array(a, dtype=np.datetime64)
#date.astype('datetime64[Y]')
#date.astype('datetime64[M]')
#date.astype('datetime64[D]')
data[...,0]=date.astype('datetime64[Y]')
print(data)

print (data[np.where(data[...,0]=="2010")])
data2010=data[np.where(data[...,0]=="2010")]
print (data2010[np.argmax(np.array(data2010[...,1],dtype=float))])

[['2019' '292.1' '299' ... '297.65' '19514041' '57796.86']
 ['2019' '295' '295.55' ... '291.1' '17548347' '51393.24']
 ['2019' '299.1' '302.5' ... '293.9' '25559853' '76220.1']
 ...
 ['1998' '285' '290.25' ... '289.15' '3632600' '10436.93']
 ['1998' '282' '288.4' ... '284.35' '4979900' '14231.55']
 ['1998' '278.45' '280.9' ... '279.95' '591700' '1654.91']]
[['2019' '292.1' '299' ... '297.65' '19514041' '57796.86']
 ['2019' '295' '295.55' ... '291.1' '17548347' '51393.24']
 ['2019' '299.1' '302.5' ... '293.9' '25559853' '76220.1']
 ...
 ['1998' '285' '290.25' ... '289.15' '3632600' '10436.93']
 ['1998' '282' '288.4' ... '284.35' '4979900' '14231.55']
 ['1998' '278.45' '280.9' ... '279.95' '591700' '1654.91']]
[['2010' '2754' '2827.45' ... '2811.9' '1962414' '54881.76']
 ['2010' '2751' '2780.45' ... '2749.65' '2106254' '58124.18']
 ['2010' '2735' '2763.2' ... '2755.2' '924155' '25404.92']
 ...
 ['2010' '2297' '2315' ... '2305.8' '1452793' '33439.2']
 ['2010' '2308' '2310' ... '2292.05' '