## Day 18 

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,6,2,2,1,35,2])
y = np.unique(x)

In [5]:
print(y)
print(type(y))

[ 1  2  3  4  6 35]
<class 'numpy.ndarray'>


In [6]:
print(np.argsort(y))

[0 1 2 3 4 5]


In [7]:
print(y.argsort()[-3:])

[3 4 5]


In [8]:
print(y.argsort()[-3:][::-1])

[5 4 3]


In [11]:
a =y.argsort()[-3:][::-1]
for i in a:
    print(y[i])

35
6
4


## HeapQ Library

In [12]:
import heapq

In [15]:
heapq.nlargest(3,range(len(y)),y.take)

[5, 4, 3]

In [16]:
print(np.argmax(y))
print(np.argmin(y))

5
0
