# Day 13

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(x[...,[1,2]])

[[2 3]
 [5 6]
 [8 9]]


In [6]:
print(x[x>5])

[6 7 8 9]


In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)

[ 4 10 18]


In [8]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [9]:
a = 10
print(bin(a))

0b1010


In [10]:
print(np.bitwise_and(13,17))

1


In [11]:
print(np.invert(np.array([13],dtype = np.uint8)))

[242]


In [13]:
print(np.binary_repr(13,width = 5))

01101


In [15]:
a = np.arange(0,12).reshape(3,4)

In [17]:
print(a)
print()
print(a.T)
print()
print(a.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [18]:
a = np.arange(0,12).reshape(3,-1)
b = np.arange(13,25).reshape(3,-1)

In [21]:
print(a)
print()
print(b)
print()
print(np.concatenate((a,b)))
print()
print(np.concatenate((a,b),axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 0  1  2  3 13 14 15 16]
 [ 4  5  6  7 17 18 19 20]
 [ 8  9 10 11 21 22 23 24]]


In [25]:
## Split Function

a = np.arange(0,12)
b = np.split(a,4)
print(b)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [28]:
c = np.split(a,[4,8])
print(c)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [37]:
a = a.reshape(3,-1)
print(a)
print()
"""Print minimum and maximum value in different dimensions"""
print("Maximum:")
print()
print(np.amax(a,axis = 0))
print()
print(np.amax(a,axis = 1))
print()
print("Minimum:")
print()
print(np.amin(a,axis = 0))
print()
print(np.amin(a,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Maximum:

[ 8  9 10 11]

[ 3  7 11]

Minimum:

[0 1 2 3]

[0 4 8]


### Mean Median and Mode 

In [49]:
a = np.arange(0,12).reshape(3,-1)

In [51]:
print(np.median(a))
print(np.median(a,axis = 0))
print(np.median(a,axis = 1))

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [53]:
print(np.mean(a))
print(np.mean(a,axis=1))
print(np.mean(a,axis=0))

5.5
[1.5 5.5 9.5]
[4. 5. 6. 7.]


In [56]:
np.average([4,3,2,1],weights = [1,2,3,4],returned = True)

(2.0, 10.0)

### Sorting

In [60]:
a = np.array([2,3,1,4,1,3,6,8,9,3,2,4,])
b = np.sort(a) ## does not effect a directly

In [61]:
print(b)

[1 1 2 2 3 3 3 4 4 6 8 9]


In [64]:
dt = np.dtype([('name','S10'),('age',int)])

In [67]:
a = np.array([('Dinesh',22),('Kunal',21),('Bharpur',24)],dtype = dt)

In [68]:
print(np.sort(a,order='age'))
print(np.sort(a,order='name'))

[(b'Kunal', 21) (b'Dinesh', 22) (b'Bharpur', 24)]
[(b'Bharpur', 24) (b'Dinesh', 22) (b'Kunal', 21)]


### Where Clause

In [69]:
x = np.arange(9).reshape(3,-1)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [70]:
y = np.where(x>3)
print(y)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


In [71]:
print(x[y])

[4 5 6 7 8]


In [72]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [73]:
cond = np.mod(x,2) == 0

In [74]:
print(x[cond])

[0 2 4 6 8]


In [75]:
print(cond)

[[ True False  True]
 [False  True False]
 [ True False  True]]


In [79]:
print(np.extract(cond,x))

[0 2 4 6 8]
